### ISSUE TITLE
Add more TargetFrameworks please

### ISSUE THREAD

**Issue by StefH** [AVVI94/ASN1Decoder#1]
Can you please add more TargetFrameworks so that this library can also be used in:

- net45
- net461
- net47
- netstandard1.3
- netstandard2.0
- netstandard2.1

**Comment by AVVI94** [comment]
Added (d93f8a68e92c8bdf654e1dc41fc044aded0e656e)

I tested it on net45, so if you encounter any issues, please let me know.
